apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubernetes-deployment
  labels:
    app: kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kubernetes
  template:
    metadata:
      labels:
        app: kubernetes
    spec:
      containers:
      - name: kubernetes
        image: docker pull dcurrotto/kubernetes
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: kubernetes-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: kubernetes
